set_property SRC_FILE_INFO {cfile:C:/Users/52853/Desktop/VivadoProj/ZDYZ/Proj1_LED/prj/Project2_LEDFlow.srcs/constrs_1/new/led_flow.xdc rfile:../../../Project2_LEDFlow.srcs/constrs_1/new/led_flow.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L15 [get_ports {led[1]}]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H15 [get_ports {led[0]}]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U18 [get_ports sys_clk]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N15 [get_ports sys_rst_n]
