set_property SRC_FILE_INFO {cfile:C:/Users/52853/Desktop/VivadoProj/ZDYZ/Proj1_LED/prj/Project1_LED.srcs/constrs_1/new/led.xdc rfile:../../../Project1_LED.srcs/constrs_1/new/led.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L14 [get_ports key]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H15 [get_ports led]
